# Generated by Django 5.1.2 on 2024-10-11 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_projects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
