# Generated by Django 5.1.2 on 2024-10-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_categories_category_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='categories',
            name='category_id',
        ),
    ]
