# Generated by Django 5.1.2 on 2024-10-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
